# Location of top-level MicroPython directory
# Set the environment variable MPY_DIR if you don't want to edit the Makefile
# make MPY_DIR=$HOME/micropython
MPY_DIR ?= micropython/

# Name of module
MOD = framebuddy

# Source files (.c or .py)
SRC = framebuddy.c

# Architecture to build for (x86, x64, armv6m, armv7m, xtensa, xtensawin)
ARCH = armv6m

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk